### ISSUE TITLE
Adding new headers overrides default ones

### ISSUE THREAD

**Issue by hojgr** [mschae/cors_plug#13]
Hello,

thanks for the plug, really useful. But i've ran into an issue.

I need to have custom header, X-Auth-Token. I've changed it in my endpoint.ex like this

    plug CORSPlug, origin: "http://localhost:4200", headers: ["X-Auth-Token"]

And I'm faced with this error in chrome:
    Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response

I fiddled around trying to find what can be causing this (expecting it to be my issue) but I found nothing. When I add the header, it breaks down. I've dove into cors_plug code and sure enough, there are defaults and those defaults are merged.

    def init(options) do
      IO.inspect Dict.merge defaults, options
    end

This yields
>[credentials: true, max_age: 1728000, expose: [], methods: ["GET", "POST", "PUT", "PATCH", origin: "http://localhost:4200", headers: ["X-AUTH-TOKEN"]]

The headers are overriden.

Am I just using it wrong or is this not an unexpected behaviour? Should there be a deep merge?

My temporary fix is:
```
plug CORSPlug, [
  origin: "http://localhost:4200", 
  headers: ["X-Auth-Token" | CORSPlug.defaults()[:headers]]
  ]
```
But I do not think this is the correct solution.

In case this is in fact a bug I'm willing to send in a pull request.

**Comment by mschae** [comment]
@hojgr Thanks for your kind words.

As for the behaviour you are seeing - that's expected and by design. Defaults are defaults, by providing your own values overrides the defaults. This is standard in every package I've seen.

My reasoning is that you might want only allow a subset of the default headers. Maybe you explicitly don't want to allow `Content-Type` headers. Furthermore I like the "explicitness" of this solution. I am using it myself.

The only thing I could think of is to provide a key similar to `additional_headers:`. But I don't believe that would be very intuitive.

So while this might be a small consolation, maybe it's a tad nicer if you left out the parens:

```Elixir
plug CORSPlug, [
  origin: "http://localhost:4200", 
  headers: ["X-Auth-Token" | CORSPlug.defaults[:headers]]
  ]
```

Any further feedback and ideas are very welcome!

**Comment by hojgr** [comment]
Thanks for answers. The explicitness is indeed nice and I did not think about the use case where not having defaults is required.

Thanks.

**Comment by mschae** [comment]
Glad I could help.

Thanks again for your feedback and please let me know if there is anything I can improve on. 

Cheers

**Comment by oppai** [comment]
It doesn't work
https://stackoverflow.com/questions/36713069/elixir-phoenix-how-to-use-third-party-modules-in-config-files
